version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017" # Expose MongoDB on localhost:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root # Set the root username
      MONGO_INITDB_ROOT_PASSWORD: example # Set the root password
    volumes:
      - mongodb_data:/data/db # Persist MongoDB data

  app:
    container_name: shop-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://root:example@mongodb:27017/shop?authSource=admin
    depends_on:
      - mongodb
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  mongodb_data: